from typing import Protocol

from glanceflow.device.models import CapturedImage, DeviceCapabilities, HUDMessage, VoiceCommand


class CameraAdapter(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def capture(self) -> CapturedImage: ...
    def healthcheck(self) -> bool: ...
    def get_capabilities(self) -> DeviceCapabilities: ...


class VoiceAdapter(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def next_command(self) -> VoiceCommand | None: ...
    def healthcheck(self) -> bool: ...


class HUDAdapter(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def display(self, message: HUDMessage) -> None: ...
    def clear(self) -> None: ...
    def healthcheck(self) -> bool: ...
