from pathlib import Path
from typing import Protocol

from glanceflow.ocr.models import OcrResult


class VisionAdapter(Protocol):
    def recognize(self, image_path: Path, source_frame_id: str) -> OcrResult: ...
    def healthcheck(self) -> bool: ...
    def get_version(self) -> str: ...
    def get_capabilities(self) -> set[str]: ...
