from enum import StrEnum


class NoticeType(StrEnum):
    EVENT_NOTICE = "EVENT_NOTICE"
    EVENT_WITH_DEADLINE = "EVENT_WITH_DEADLINE"


class SafetyGateStatus(StrEnum):
    READY_TO_CONFIRM = "READY_TO_CONFIRM"
    NEED_USER_INPUT = "NEED_USER_INPUT"
    CONTRADICTION_BLOCKED = "CONTRADICTION_BLOCKED"
    RECAPTURE_REQUIRED = "RECAPTURE_REQUIRED"


class ValidationSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    BLOCKING = "BLOCKING"


class DeadlineRole(StrEnum):
    REGISTRATION = "REGISTRATION"
    APPLICATION = "APPLICATION"
    CHECK_IN = "CHECK_IN"
    ENTRY = "ENTRY"


class TemporalType(StrEnum):
    EVENT_START = "EVENT_START"
    EVENT_END = "EVENT_END"
    REGISTRATION_DEADLINE = "REGISTRATION_DEADLINE"
    SUBMISSION_DEADLINE = "SUBMISSION_DEADLINE"
    CHECK_IN_TIME = "CHECK_IN_TIME"
    PUBLICATION_TIME = "PUBLICATION_TIME"
    CANCELLATION_TIME = "CANCELLATION_TIME"
    RESCHEDULED_TIME = "RESCHEDULED_TIME"
    UNKNOWN_TEMPORAL_FIELD = "UNKNOWN_TEMPORAL_FIELD"


class TemporalNormalizationStatus(StrEnum):
    NORMALIZED = "NORMALIZED"
    UNRESOLVED = "UNRESOLVED"
    CONFLICTING = "CONFLICTING"
    CANCELLED = "CANCELLED"
    EVIDENCE_INCOMPLETE = "EVIDENCE_INCOMPLETE"
