from __future__ import annotations

import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def generate(target: Path = ROOT / "docs/competition/final-metrics.md") -> str:
    value = json.loads((ROOT / "outputs/agent/value_analysis/system_comparison.json").read_text(encoding="utf-8"))
    metrics = value["metrics"]
    demo = json.loads((ROOT / "outputs/demo/scenario_results.json").read_text(encoding="utf-8"))["results"]
    repeats = json.loads((ROOT / "outputs/demo/repeatability_results.json").read_text(encoding="utf-8"))
    with (ROOT / "outputs/demo/latency_results.csv").open(encoding="utf-8-sig", newline="") as handle:
        latency = list(csv.DictReader(handle))
    system_names = (("direct_execution", "Direct Execution"), ("existing_pipeline", "Existing Pipeline"), ("optimized_agent", "Optimized Agent"))
    lines = [
        "# Final metrics", "", "> Generated by `scripts/generate_final_metrics.py` from checked-in program outputs; do not hand-edit values.", "",
        "## Stage 5 — fixed-seed evaluation", "", "- Dataset: **46/46 SYNTHETIC samples** in `evaluation/dataset/`.",
        "- Source: `outputs/evaluation/metric_audit.json` and `outputs/evaluation/final_scorecard.json`.",
        "- Environment: Windows local CPU simulator; not physical-glasses performance.", "", "## Stage 7 — same 20 scenarios per system", "",
        "| System | Wrong execution | Goal completion | Recovery |", "|---|---:|---:|---:|",
    ]
    for key, label in system_names:
        wrong = metrics[key]["wrong_execution_rate"]
        goal = metrics[key]["successful_goal_completion_rate"]
        recovery = metrics[key]["recovery_success_rate"]
        lines.append(f"| {label} | {wrong['numerator']}/{wrong['denominator']} | {goal['numerator']}/{goal['denominator']} | {recovery['numerator']}/{recovery['denominator']} |")
    lines.extend([
        "", "All 20 are local deterministic **SYNTHETIC / fault-injection scenarios**, not users, real campus notices, real glasses, or Google Calendar statistics.",
        "The Agent result 0/20 means no wrong execution was observed in this set; it does not establish absolute safety.", "", "## Stage 14 — competition simulator", "",
        f"- Demo scenarios executed: **{len(demo)}/8**.",
        f"- Core repeatability runs: **{len(repeats['results'])} × {repeats['runs_per_scenario']} = {sum(len(row['runs']) for row in repeats['results'])} simulator runs**.",
        f"- Wrong side effects observed: **{sum(row['wrong_side_effects'] for row in repeats['results'])}/60**.",
        f"- Duplicate events observed: **{sum(row['duplicate_events'] for row in repeats['results'])}/60**.",
        f"- Unclean transactions observed: **{sum(row['unclean_transactions'] for row in repeats['results'])}/60**.",
        f"- Crashes observed: **{sum(row['crashes'] for row in repeats['results'])}/60**.",
        "", "In six core simulator scenarios repeated 10 times each, no wrong side effect, duplicate event, unclean transaction, or crash was observed. This is a **SIMULATOR REPEATABILITY TEST**, not a system success rate or user reliability result.",
        "", "### Demo end-to-end latency", "", "| Scenario | End-to-end (ms) |", "|---|---:|",
    ])
    lines.extend(f"| {row['scenario_id']} | {float(row['end_to_end_ms']):.3f} |" for row in latency)
    lines.extend(["", "Latency was measured on the current Windows local CPU simulator. It does not represent Rokid or other physical-glasses latency."])
    text = "\n".join(lines) + "\n"
    target.write_text(text, encoding="utf-8")
    return text


if __name__ == "__main__":
    generate()
